{{- if .Values.istio.envoyfilter.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ template "APP.name" . }}
spec:
  workloadLabels:
    app: {{ template "APP.name" . }}
    filters:
    - listenerMatch:
        portNumber: CHANGEME
        listenerType: SIDECAR_INBOUND
        listenerProtocol: HTTP
      insertPosition:
        index: FIRST
      filterType: HTTP
      filterName: "envoy.grpc_web"
      filterConfig: {}
{{- end -}}