{{- if .Values.secretDB.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "APP.name" . }}-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=

  MONGO_USER: cm9vdA==
  MONGO_PASSWORD: cGFzc3dvcmQ=

  MINIO_ACCESS: bWluaW9fYWNjZXNz
  MINIO_SECRET: VGVzOXRpbmc=

  RABBITMQ_USER: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
{{- end -}}