{{- if .Values.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "APP.name" . }}
spec:
{{- if  not .Values.istio.virtualservice.host  }}
  hosts:
  - {{ .Values.global.baseUrl }}
{{- else }}
  hosts:
  - {{ .Values.istio.virtualservice.host }}.{{ .Values.global.baseUrl }}
{{- end }}
  gateways: 
  - {{ .Values.global.gateway }}
  http:
{{ toYaml .Values.istio.virtualservice.http | indent 2 }}
{{- end -}}
