query companiesByOrgID($organisationIDs: [ID!]!) {
  companiesByOrganisationIDs(organisationIDs: $organisationIDs) {
    name
    bgURL
    id
    companyLogo {
      aPIID
    }
    organisationID
  }
}
