query workspacesByID($id: ID!) {
  workspaceByID(id: $id) {
    id
    name
    wsUsers {
      wsUsers {
        id
        user {
          id
          subject
          profile {
            groups
            userID
            fullName
            subject
            email
            pictureURL
            title
          }
        }
      }
    }
    description
    coverURL
    startDate
    endDate
    createdBy {
      id
      subject
    }
  }
}
