export const dataTableOp = [
  {
    companyName: 'Title Sould Be Mentioned',
    block: '123456',
    submissionDate: '11-06-2019',
    submissionBy: 'Maryam Khan',
    contractTitle: 'Title should be mentioned',
    contractType: 'Major Contract',
    status: 'Pending',
    id: 1,
  },
  {
    companyName: 'Title Sould Be Mentioned',
    block: '123456',
    submissionDate: '11-06-2019',
    submissionBy: 'Maryam Khan',
    contractTitle: 'Title should be mentioned',
    contractType: 'Major Contract',
    status: 'Pending',
    id: 2,
  },
]
export const dataTableTbc = [
  {
    companyName: 'Title Sould Be Mentioned',
    block: '123456',
    submissionDay: 'Tuesday',
    submissionDate: '11-06-2019',
    submissionBy: 'Maryam Khan',
    contractTitle: 'Title should be mentioned',
    contractType: 'Major Contract',
    status: 'Approved',
    id: 1,
  },
  {
    companyName: 'Title Sould Be Mentioned',
    block: '123456',
    submissionDay: 'Tuesday',
    submissionDate: '11-06-2019',
    submissionBy: 'Maryam Khan',
    contractTitle: 'Title should be mentioned',
    contractType: 'Major Contract',
    status: 'Passed To Agenda',
    id: 2,
  },
  {
    companyName: 'Title Sould Be Mentioned',
    block: '123456',
    submissionDay: 'Tuesday',
    submissionDate: '11-06-2019',
    submissionBy: 'Maryam Khan',
    contractTitle: 'Title should be mentioned',
    contractType: 'Major Contract',
    status: 'Not Discussed',
    id: 3,
  },
  {
    companyName: 'Title Sould Be Mentioned',
    block: '123456',
    submissionDay: 'Tuesday',
    submissionDate: '11-06-2019',
    submissionBy: 'Maryam Khan',
    contractTitle: 'Title should be mentioned',
    contractType: 'Major Contract',
    status: 'Under Review',
    id: 4,
  },
  {
    companyName: 'Title Sould Be Mentioned',
    block: '123456',
    submissionDay: 'Tuesday',
    submissionDate: '11-06-2019',
    submissionBy: 'Maryam Khan',
    contractTitle: 'Title should be mentioned',
    contractType: 'Major Contract',
    status: 'Under Review',
    id: 5,
  },
  {
    companyName: 'Title Sould Be Mentioned',
    block: '123456',
    submissionDay: 'Tuesday',
    submissionDate: '11-06-2019',
    submissionBy: 'Maryam Khan',
    contractTitle: 'Title should be mentioned',
    contractType: 'Major Contract',
    status: 'Rejected',
    id: 6,
  },
  {
    companyName: 'Title Sould Be Mentioned',
    block: '123456',
    submissionDay: 'Tuesday',
    submissionDate: '11-06-2019',
    submissionBy: 'Maryam Khan',
    contractTitle: 'Title should be mentioned',
    contractType: 'Major Contract',
    status: 'Rejected',
    id: 7,
  },
]
