export const reportsList = [
  {
    filename: 'Reporting Template A.xlsx',
    id: 1,
    url: '/upload/reporting-template',
    type: 'xlsx',
  },
  {
    filename: 'Reporting Template A.xlsx',
    id: 2,
    url: '/upload/reporting-template',
    type: 'xlsx',
  },
  {
    filename: 'Reporting Template A.xlsx',
    id: 3,
    url: '/upload/reporting-template',
    type: 'xlsx',
  },
  {
    filename: 'Reporting Template A.xlsx',
    id: 4,
    url: '/upload/reporting-template',
    type: 'xlsx',
  },
  {
    filename: 'Reporting Template B.xlsx',
    id: 5,
    url: '/upload/reporting-template',
    type: 'xlsx',
  },
  {
    filename: 'Reporting Template B.xlsx',
    id: 6,
    url: '/upload/reporting-template',
    type: 'xlsx',
  },
  {
    filename: 'Reporting Template B.xlsx',
    id: 7,
    url: '/upload/reporting-template',
    type: 'xlsx',
  },
  {
    filename: 'Reporting Template C.xlsx',
    id: 8,
    url: '/upload/reporting-template',
    type: 'xlsx',
  },
]

export const configTable = [
  {
    name: 'FILE NAME',
    dataKey: 'filename',
    align: 'left',
    width: 60,
  },
  {
    name: 'COMPANY NAME',
    dataKey: 'companyName',
    align: 'left',
    width: 45,
  },

  {
    name: 'BLOCK',
    dataKey: 'block',
    align: 'left',
    width: 45,
  },
  {
    name: 'SUBMISSION DATE',
    dataKey: 'uploadDate',
    align: 'left',
    width: 45,
  },

  {
    name: 'SUBMITTED BY',
    align: 'left',
    dataKey: 'author',
    width: 45,
  },

  {
    name: 'REFERENCE DATE',
    dataKey: 'referenceDate',
    align: 'left',
    width: 45,
  },
]
export const dataReports = [
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
  {
    filename: 'Reporting Template A',
    companyName: 'Company',
    block: 12,
    submissionDate: '22-03-2020',
    createdBy: 'Muhammed Ahmed',
    year: '23-03-2020',
  },
]

export const blockList = [10, 11, 12, 13, 14]
