export const additionRecordDetailsConfigs = () => [
  {
    label: 'Material Name',
    key: 'materialName',
    width: '200',
    icon: 'mdi mdi-spellcheck',
    type: 'text',
  },
  {
    label: 'Material Category',
    key: 'materialCategory',
    width: '200',
    type: 'text',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Material Description',
    key: 'materialDescription',
    width: '400',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Classification',
    key: 'classification',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Quantity',
    key: 'quantity',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Measurement Unit',
    key: 'measurementUnit',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Storage Location',
    key: 'storageLocation',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Date of Purchase',
    key: 'dateOfPurchase',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Book Value',
    key: 'bookValue',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Estimated Current Value',
    key: 'estimatedCurrentValue',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Serial Number',
    key: 'serialNumber',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Material Location',
    key: 'materialLocation',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Inspection Date',
    key: 'inspectionDate',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Material Condition',
    key: 'materialCondition',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Weight',
    key: 'weight',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Average Length',
    key: 'averageLength',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Item Weight',
    key: 'itemWeight',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Total Weight',
    key: 'mTCertificate',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'MT Certificate',
    key: 'mTCertificate',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Reasons for Sale / Write - off',
    key: 'reasonsForSale',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
  {
    label: 'Remarks',
    key: 'remarks',
    width: '200',
    icon: 'mdi mdi-spellcheck',
  },
]
